package com.poidevin.UI;

import com.poidevin.beans.org.openstreetmap.gui.jmapviewer.events.JMVCommandEvent;
import com.poidevin.beans.org.openstreetmap.gui.jmapviewer.interfaces.JMapViewerEventListener;
import com.poidevin.controller.VRPController;

/**
 *
 * @author Francois POIDEVIN-MERDRIGNAC
 */
public class VRPUI extends javax.swing.JFrame implements JMapViewerEventListener
{
	
	private VRPController clsController;

	/**
	 * Creates new form VRPUI
	 */
	public VRPUI()
	{
		super("VRP Map");
		initComponents();
		this.clsController = new VRPController();
		initController();
	}

	private void initController()
	{
		clsController.setView( this );
		clsController.init();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSplitPane = new javax.swing.JSplitPane();
        jPanCommand = new javax.swing.JPanel();
        jXTskPanVRPCalc = new org.jdesktop.swingx.JXTaskPane();
        jPanVRPCalc = new javax.swing.JPanel();
        jPanSpritDepot = new javax.swing.JPanel();
        jScrollPanVehicle = new javax.swing.JScrollPane();
        grdDepot = new org.jdesktop.swingx.JXTable();
        jChkBoxInfFleetFlag = new javax.swing.JCheckBox();
        jBtnAddDepot = new javax.swing.JButton();
        jPanSpritLocation = new javax.swing.JPanel();
        jScrollPanParcels = new javax.swing.JScrollPane();
        grdLocation = new org.jdesktop.swingx.JXTable();
        btnProcess = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanOSRM = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        chkTripDisplay = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnTripPrev = new javax.swing.JButton();
        btnTripnext = new javax.swing.JButton();
        lblTripDistanceVal = new javax.swing.JLabel();
        lblTripDurationVal = new javax.swing.JLabel();
        panJSprit = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        chkDisplayRtCstr = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        lblDistanceRtCstrVal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDurationRtCstrVal = new javax.swing.JLabel();
        btnSpritNext = new javax.swing.JButton();
        btnSpritPrev = new javax.swing.JButton();
        jXTskPanLogs = new org.jdesktop.swingx.JXTaskPane();
        jPanLogs = new javax.swing.JPanel();
        scrollPaneLog = new javax.swing.JScrollPane();
        txtAreaLog = new javax.swing.JTextArea();
        jPanMapViewer = new javax.swing.JPanel();
        jPanMap = new javax.swing.JPanel();
        jMapViewer = new com.poidevin.beans.org.openstreetmap.gui.jmapviewer.JMapViewer();
        jPanInfo = new javax.swing.JPanel();
        jLblZoom = new javax.swing.JLabel();
        jLblZoomVal = new javax.swing.JLabel();
        jLblScale = new javax.swing.JLabel();
        jLblScaleVal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane.setDividerLocation(350);
        jSplitPane.setDividerSize(7);
        jSplitPane.setMinimumSize(new java.awt.Dimension(9, 3));
        jSplitPane.setOneTouchExpandable(true);
        jSplitPane.setPreferredSize(new java.awt.Dimension(647, 1454));

        jXTskPanVRPCalc.setTitle("VRP Calculating");

        jPanSpritDepot.setBorder(javax.swing.BorderFactory.createTitledBorder("Jsprit - Depot/Vehicle definition"));

        grdDepot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null}
            },
            new String []
            {
                "Id", "Capacity", "Latitude", "Longitude", "Cost per Distance", "Cost per Travel"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        grdDepot.setHorizontalScrollEnabled(true);
        grdDepot.setSortable(false);
        grdDepot.getTableHeader().setReorderingAllowed(false);
        jScrollPanVehicle.setViewportView(grdDepot);

        jChkBoxInfFleetFlag.setText("Infinite Fleet");

        jBtnAddDepot.setText("Add");

        javax.swing.GroupLayout jPanSpritDepotLayout = new javax.swing.GroupLayout(jPanSpritDepot);
        jPanSpritDepot.setLayout(jPanSpritDepotLayout);
        jPanSpritDepotLayout.setHorizontalGroup(
            jPanSpritDepotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanSpritDepotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChkBoxInfFleetFlag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnAddDepot))
        );
        jPanSpritDepotLayout.setVerticalGroup(
            jPanSpritDepotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanSpritDepotLayout.createSequentialGroup()
                .addGroup(jPanSpritDepotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBoxInfFleetFlag)
                    .addComponent(jBtnAddDepot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanSpritLocation.setBorder(javax.swing.BorderFactory.createTitledBorder("JSprit - Locations definition"));

        grdLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Id", "Quantity", "Latitude", "Longitude", "Service Duration", "Time Windows Start", "Time Windows End"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        grdLocation.setHorizontalScrollEnabled(true);
        grdLocation.setSortable(false);
        grdLocation.getTableHeader().setReorderingAllowed(false);
        jScrollPanParcels.setViewportView(grdLocation);

        javax.swing.GroupLayout jPanSpritLocationLayout = new javax.swing.GroupLayout(jPanSpritLocation);
        jPanSpritLocation.setLayout(jPanSpritLocationLayout);
        jPanSpritLocationLayout.setHorizontalGroup(
            jPanSpritLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanParcels, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanSpritLocationLayout.setVerticalGroup(
            jPanSpritLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanSpritLocationLayout.createSequentialGroup()
                .addComponent(jScrollPanParcels, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnProcess.setText("Calculate");

        btnReset.setText("Reset");

        jPanOSRM.setBorder(javax.swing.BorderFactory.createTitledBorder("Routing results without constraints"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(" Optimize OSRM"));

        chkTripDisplay.setText("Display");

        jLabel10.setText("Distance :");

        jLabel11.setText("Duration :");

        btnTripPrev.setText("<< Previous");

        btnTripnext.setText("Next >>");
        btnTripnext.setPreferredSize(new java.awt.Dimension(93, 23));

        lblTripDistanceVal.setText("-");

        lblTripDurationVal.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTripPrev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkTripDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTripDistanceVal)
                    .addComponent(lblTripDurationVal)
                    .addComponent(btnTripnext, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTripDisplay)
                    .addComponent(jLabel10)
                    .addComponent(lblTripDistanceVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblTripDurationVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTripPrev)
                    .addComponent(btnTripnext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanOSRMLayout = new javax.swing.GroupLayout(jPanOSRM);
        jPanOSRM.setLayout(jPanOSRMLayout);
        jPanOSRMLayout.setHorizontalGroup(
            jPanOSRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanOSRMLayout.setVerticalGroup(
            jPanOSRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panJSprit.setBorder(javax.swing.BorderFactory.createTitledBorder("Routing results with constraints"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Optimize JSprit"));

        chkDisplayRtCstr.setText("Display");

        jLabel8.setText("Distance : ");

        lblDistanceRtCstrVal.setText("-");

        jLabel13.setText("Duration :");

        lblDurationRtCstrVal.setText("-");

        btnSpritNext.setText("Next >>");
        btnSpritNext.setPreferredSize(new java.awt.Dimension(93, 23));

        btnSpritPrev.setText("<< Previous");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(chkDisplayRtCstr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDurationRtCstrVal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDistanceRtCstrVal)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnSpritPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSpritNext, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDisplayRtCstr)
                    .addComponent(jLabel8)
                    .addComponent(lblDistanceRtCstrVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblDurationRtCstrVal))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSpritPrev)
                        .addComponent(btnSpritNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panJSpritLayout = new javax.swing.GroupLayout(panJSprit);
        panJSprit.setLayout(panJSpritLayout);
        panJSpritLayout.setHorizontalGroup(
            panJSpritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panJSpritLayout.setVerticalGroup(
            panJSpritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanVRPCalcLayout = new javax.swing.GroupLayout(jPanVRPCalc);
        jPanVRPCalc.setLayout(jPanVRPCalcLayout);
        jPanVRPCalcLayout.setHorizontalGroup(
            jPanVRPCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanOSRM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanVRPCalcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcess)
                .addContainerGap())
            .addComponent(panJSprit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanSpritDepot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanSpritLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanVRPCalcLayout.setVerticalGroup(
            jPanVRPCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanVRPCalcLayout.createSequentialGroup()
                .addComponent(jPanSpritDepot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanSpritLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanVRPCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanOSRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panJSprit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTskPanVRPCalc.getContentPane().add(jPanVRPCalc);

        jXTskPanLogs.setTitle("Logs");
        jXTskPanLogs.setToolTipText("");

        scrollPaneLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Logs"));
        scrollPaneLog.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPaneLog.setPreferredSize(new java.awt.Dimension(333, 137));

        txtAreaLog.setColumns(20);
        txtAreaLog.setRows(5);
        txtAreaLog.setMinimumSize(null);
        txtAreaLog.setPreferredSize(null);
        scrollPaneLog.setViewportView(txtAreaLog);

        javax.swing.GroupLayout jPanLogsLayout = new javax.swing.GroupLayout(jPanLogs);
        jPanLogs.setLayout(jPanLogsLayout);
        jPanLogsLayout.setHorizontalGroup(
            jPanLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
            .addGroup(jPanLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollPaneLog, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );
        jPanLogsLayout.setVerticalGroup(
            jPanLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
            .addGroup(jPanLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollPaneLog, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );

        jXTskPanLogs.getContentPane().add(jPanLogs);

        javax.swing.GroupLayout jPanCommandLayout = new javax.swing.GroupLayout(jPanCommand);
        jPanCommand.setLayout(jPanCommandLayout);
        jPanCommandLayout.setHorizontalGroup(
            jPanCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTskPanVRPCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jXTskPanLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanCommandLayout.setVerticalGroup(
            jPanCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanCommandLayout.createSequentialGroup()
                .addComponent(jXTskPanVRPCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTskPanLogs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanCommand);

        javax.swing.GroupLayout jPanMapLayout = new javax.swing.GroupLayout(jPanMap);
        jPanMap.setLayout(jPanMapLayout);
        jPanMapLayout.setHorizontalGroup(
            jPanMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMapViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanMapLayout.setVerticalGroup(
            jPanMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMapViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        jLblZoom.setText("Zoom :");

        jLblZoomVal.setText("-");
        jLblZoomVal.setMaximumSize(new java.awt.Dimension(10, 14));

        jLblScale.setText("Meters/Pixels :");
        jLblScale.setName(""); // NOI18N

        jLblScaleVal.setText("-");
        jLblScaleVal.setMaximumSize(new java.awt.Dimension(25, 14));

        javax.swing.GroupLayout jPanInfoLayout = new javax.swing.GroupLayout(jPanInfo);
        jPanInfo.setLayout(jPanInfoLayout);
        jPanInfoLayout.setHorizontalGroup(
            jPanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblZoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblZoomVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblScale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblScaleVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        jPanInfoLayout.setVerticalGroup(
            jPanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblZoom)
                    .addComponent(jLblZoomVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblScale)
                    .addComponent(jLblScaleVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanMapViewerLayout = new javax.swing.GroupLayout(jPanMapViewer);
        jPanMapViewer.setLayout(jPanMapViewerLayout);
        jPanMapViewerLayout.setHorizontalGroup(
            jPanMapViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanMap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanMapViewerLayout.setVerticalGroup(
            jPanMapViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanMapViewerLayout.createSequentialGroup()
                .addComponent(jPanMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane.setRightComponent(jPanMapViewer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//Accessors
	public javax.swing.JLabel getMperpLabelValue()
	{
		return jLblScaleVal;
	}
	public javax.swing.JLabel getZoomValue()
	{
		return jLblZoomVal;
	}
	public com.poidevin.beans.org.openstreetmap.gui.jmapviewer.JMapViewer getMap()
	{
		return jMapViewer;
	}
	public javax.swing.JButton getBtnProcess() {
		return btnProcess;
	}

	public javax.swing.JButton getBtnReset() {
		return btnReset;
	}

	public javax.swing.JButton getBtnSpritPrev() {
		return btnSpritPrev;
	}

	public javax.swing.JButton getBtnSpritNext() {
		return btnSpritNext;
	}

	public javax.swing.JButton getBtnTripPrev() {
		return btnTripPrev;
	}

	public javax.swing.JButton getBtnTripnext() {
		return btnTripnext;
	}

	public javax.swing.JCheckBox getChkDisplayRtCstr() {
		return chkDisplayRtCstr;
	}

	public javax.swing.JCheckBox getChkTripDisplay() {
		return chkTripDisplay;
	}

	public javax.swing.JButton getjBtnAddDepot() {
		return jBtnAddDepot;
	}

	public javax.swing.JCheckBox getjChkBoxInfFleetFlag() {
		return jChkBoxInfFleetFlag;
	}

	public org.jdesktop.swingx.JXTable getGrdDepot() {
		return grdDepot;
	}

	public org.jdesktop.swingx.JXTable getGrdLocation() {
		return grdLocation;
	}

	public javax.swing.JLabel getLblDistanceRtCstrVal() {
		return lblDistanceRtCstrVal;
	}

	public javax.swing.JLabel getLblDurationRtCstrVal() {
		return lblDurationRtCstrVal;
	}

	public javax.swing.JLabel getLblTripDistanceVal() {
		return lblTripDistanceVal;
	}

	public javax.swing.JLabel getLblTripDurationVal() {
		return lblTripDurationVal;
	}

	
	@Override
	public void processCommand(JMVCommandEvent command) {
		//TODO search why event not raised
		if (command.getCommand().equals(JMVCommandEvent.COMMAND.ZOOM) ||
				command.getCommand().equals(JMVCommandEvent.COMMAND.MOVE)) 
		{
			if (getMperpLabelValue() != null)
				getMperpLabelValue().setText(String.format("%s", getMap().getMeterPerPixel()));
			if (getZoomValue() != null)
				getZoomValue().setText(String.format("%s", getMap().getZoom()));
		}
		
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] )
	{
		/* Create and display the form */
		java.awt.EventQueue.invokeLater( new Runnable()
		{
			public void run()
			{
				new VRPUI().setVisible( true );
			}
		} );
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSpritPrev;
    private javax.swing.JButton btnSpritNext;
    private javax.swing.JButton btnTripPrev;
    private javax.swing.JButton btnTripnext;
    private javax.swing.JCheckBox chkDisplayRtCstr;
    private javax.swing.JCheckBox chkTripDisplay;
    private javax.swing.JButton jBtnAddDepot;
    private javax.swing.JCheckBox jChkBoxInfFleetFlag;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblScale;
    private javax.swing.JLabel jLblScaleVal;
    private javax.swing.JLabel jLblZoom;
    private javax.swing.JLabel jLblZoomVal;
    private com.poidevin.beans.org.openstreetmap.gui.jmapviewer.JMapViewer jMapViewer;
    private javax.swing.JPanel jPanCommand;
    private javax.swing.JPanel jPanInfo;
    private javax.swing.JPanel jPanLogs;
    private javax.swing.JPanel jPanMap;
    private javax.swing.JPanel jPanMapViewer;
    private javax.swing.JPanel jPanOSRM;
    private javax.swing.JPanel jPanSpritDepot;
    private javax.swing.JPanel jPanSpritLocation;
    private javax.swing.JPanel jPanVRPCalc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPanParcels;
    private javax.swing.JScrollPane jScrollPanVehicle;
    private javax.swing.JSplitPane jSplitPane;
    private org.jdesktop.swingx.JXTable grdDepot;
    private org.jdesktop.swingx.JXTable grdLocation;
    private org.jdesktop.swingx.JXTaskPane jXTskPanLogs;
    private org.jdesktop.swingx.JXTaskPane jXTskPanVRPCalc;
    private javax.swing.JLabel lblDistanceRtCstrVal;
    private javax.swing.JLabel lblDurationRtCstrVal;
    private javax.swing.JLabel lblTripDistanceVal;
    private javax.swing.JLabel lblTripDurationVal;
    private javax.swing.JPanel panJSprit;
    private javax.swing.JScrollPane scrollPaneLog;
    private javax.swing.JTextArea txtAreaLog;
    // End of variables declaration//GEN-END:variables
}
